// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalApp.Server.Data;

#nullable disable

namespace RentalApp.Server.Migrations
{
    [DbContext(typeof(RentalAppContext))]
    [Migration("20230620175938_SeedEquipment")]
    partial class SeedEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("ProtectiveGearRental", b =>
                {
                    b.Property<int>("ProtectiveGearId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RentalsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProtectiveGearId", "RentalsId");

                    b.HasIndex("RentalsId");

                    b.ToTable("ProtectiveGearRental");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Equipment.SportsEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFunctional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Size")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SportsEquipment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DismissalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EmploymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pesel")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[Role] & 2 = 2 OR [Role] & 4 = 4 OR [Role] & 8 = 8");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[Role] & 1 = 1");

                    b.HasIndex("SupervisorId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Aubrey",
                            LastName = "Hurworth",
                            PhoneNumber = "190684116",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = "e1",
                            FirstName = "Duncan",
                            LastName = "Agius",
                            PhoneNumber = "456100995",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = "e2",
                            FirstName = "Colby",
                            LastName = "Lisciandro",
                            PhoneNumber = "391899786",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Sherilyn",
                            LastName = "Cornewall",
                            PhoneNumber = "198315600",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = "e3",
                            FirstName = "Isadora",
                            LastName = "Casel",
                            Role = 4
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Hermina",
                            LastName = "Edgley",
                            PhoneNumber = "882627905",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = "e4",
                            FirstName = "Beckie",
                            LastName = "Fann",
                            Role = 4
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = "e5",
                            FirstName = "Shelley",
                            LastName = "Molyneaux",
                            Role = 2
                        },
                        new
                        {
                            Id = 9,
                            EmployeeId = "e6",
                            FirstName = "Yasmin",
                            LastName = "Beecker",
                            PhoneNumber = "362667890",
                            Role = 3
                        },
                        new
                        {
                            Id = 10,
                            EmployeeId = "e7",
                            FirstName = "Nollie",
                            LastName = "Anglish",
                            Role = 4
                        },
                        new
                        {
                            Id = 11,
                            EmployeeId = "e8",
                            FirstName = "Carmencita",
                            LastName = "Tattam",
                            PhoneNumber = "800838101",
                            Role = 5
                        },
                        new
                        {
                            Id = 12,
                            EmployeeId = "e9",
                            FirstName = "Lucas",
                            LastName = "Faughny",
                            Role = 2
                        });
                });

            modelBuilder.Entity("RentalApp.Shared.Models.ProtectiveGear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProtectiveGear");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EquipmentDamaged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ScheduledEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Equipment.Skates.IceSkates", b =>
                {
                    b.HasBaseType("RentalApp.Shared.Models.Equipment.SportsEquipment");

                    b.Property<string>("BladeMaterial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasToePick")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("IceSkates");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            IsFunctional = true,
                            Purpose = "Speed Skating",
                            Size = 38m,
                            BladeMaterial = "Steel",
                            HasToePick = true
                        },
                        new
                        {
                            Id = 7,
                            IsFunctional = false,
                            Purpose = "Figure Skating",
                            Size = 47m,
                            BladeMaterial = "Carbon Fiber",
                            HasToePick = true
                        },
                        new
                        {
                            Id = 9,
                            IsFunctional = true,
                            Purpose = "Speed Skating",
                            Size = 38m,
                            BladeMaterial = "Steel",
                            HasToePick = true
                        },
                        new
                        {
                            Id = 10,
                            IsFunctional = false,
                            Purpose = "Hockey",
                            Size = 43m,
                            BladeMaterial = "Carbon Fiber",
                            HasToePick = true
                        },
                        new
                        {
                            Id = 11,
                            IsFunctional = false,
                            Purpose = "Hockey",
                            Size = 47m,
                            BladeMaterial = "Steel",
                            HasToePick = false
                        },
                        new
                        {
                            Id = 13,
                            IsFunctional = true,
                            Purpose = "Figure Skating",
                            Size = 42m,
                            BladeMaterial = "Steel",
                            HasToePick = false
                        },
                        new
                        {
                            Id = 15,
                            IsFunctional = false,
                            Purpose = "Speed Skating",
                            Size = 37m,
                            BladeMaterial = "Aluminum",
                            HasToePick = false
                        },
                        new
                        {
                            Id = 16,
                            IsFunctional = true,
                            Purpose = "Hockey",
                            Size = 45m,
                            BladeMaterial = "Steel",
                            HasToePick = false
                        },
                        new
                        {
                            Id = 19,
                            IsFunctional = true,
                            Purpose = "Figure Skating",
                            Size = 42m,
                            BladeMaterial = "Plastic",
                            HasToePick = true
                        });
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Equipment.Skates.InlineSkates", b =>
                {
                    b.HasBaseType("RentalApp.Shared.Models.Equipment.SportsEquipment");

                    b.Property<string>("BearingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WheelDiameter")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("InlineSkates");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            IsFunctional = true,
                            Purpose = "Figure Skating",
                            Size = 47m,
                            BearingType = "ABEC-5",
                            WheelDiameter = 15m
                        },
                        new
                        {
                            Id = 6,
                            IsFunctional = true,
                            Purpose = "Hockey",
                            Size = 47m,
                            BearingType = "ABEC-9",
                            WheelDiameter = 88m
                        },
                        new
                        {
                            Id = 8,
                            IsFunctional = true,
                            Purpose = "Speed Skating",
                            Size = 42m,
                            BearingType = "ABEC-9",
                            WheelDiameter = 30m
                        },
                        new
                        {
                            Id = 12,
                            IsFunctional = true,
                            Purpose = "Speed Skating",
                            Size = 41m,
                            BearingType = "ABEC-7",
                            WheelDiameter = 38m
                        },
                        new
                        {
                            Id = 18,
                            IsFunctional = false,
                            Purpose = "Hockey",
                            Size = 45m,
                            BearingType = "ABEC-3",
                            WheelDiameter = 22m
                        });
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Equipment.Skates.RollerSkates", b =>
                {
                    b.HasBaseType("RentalApp.Shared.Models.Equipment.SportsEquipment");

                    b.Property<int>("WheelHardness")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("RollerSkates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFunctional = true,
                            Purpose = "Speed Skating",
                            Size = 44m,
                            WheelHardness = 36
                        },
                        new
                        {
                            Id = 2,
                            IsFunctional = false,
                            Purpose = "Figure Skating",
                            Size = 46m,
                            WheelHardness = 75
                        },
                        new
                        {
                            Id = 3,
                            IsFunctional = true,
                            Purpose = "Figure Skating",
                            Size = 47m,
                            WheelHardness = 10
                        },
                        new
                        {
                            Id = 14,
                            IsFunctional = false,
                            Purpose = "Figure Skating",
                            Size = 42m,
                            WheelHardness = 91
                        },
                        new
                        {
                            Id = 20,
                            IsFunctional = true,
                            Purpose = "Hockey",
                            Size = 43m,
                            WheelHardness = 89
                        });
                });

            modelBuilder.Entity("ProtectiveGearRental", b =>
                {
                    b.HasOne("RentalApp.Shared.Models.ProtectiveGear", null)
                        .WithMany()
                        .HasForeignKey("ProtectiveGearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Shared.Models.Rental", null)
                        .WithMany()
                        .HasForeignKey("RentalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Person", b =>
                {
                    b.HasOne("RentalApp.Shared.Models.Person", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Rental", b =>
                {
                    b.HasOne("RentalApp.Shared.Models.Person", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Shared.Models.Equipment.SportsEquipment", "Equipment")
                        .WithMany("Rentals")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Shared.Models.Insurance", "Insurance")
                        .WithOne("Rental")
                        .HasForeignKey("RentalApp.Shared.Models.Rental", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Equipment");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Equipment.SportsEquipment", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Insurance", b =>
                {
                    b.Navigation("Rental")
                        .IsRequired();
                });

            modelBuilder.Entity("RentalApp.Shared.Models.Person", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
