// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalApp.Server.Data;

#nullable disable

namespace RentalApp.Server.Migrations
{
    [DbContext(typeof(RentalAppContext))]
    partial class RentalAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");
#pragma warning restore 612, 618
        }
    }
}
